MTES-MCT/dossierfacile-backend

dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/service/ApartmentSharingServiceImpl.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/enums/FileStatus.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/mapper/ApplicationFullMapper.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/model/apartment_sharing/ApplicationModel.java

Proposal for using status instead url link and temporary fix if partner not yet using POST.

feat: use status instead url link for dossier pdf

---

dossierfacile-api-owner/src/main/java/fr/dossierfacile/api/dossierfacileapiowner/property/PropertyForm.java
dossierfacile-api-owner/src/main/java/fr/dossierfacile/api/dossierfacileapiowner/property/PropertyModel.java
dossierfacile-api-owner/src/main/java/fr/dossierfacile/api/dossierfacileapiowner/property/PropertyServiceImpl.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/entity/Property.java
dossierfacile-common-library/src/main/resources/db/migration/202303210000-add-dpe-columns-in-property.xml

energy consumption and co2 emission

feat(owner): add data to property

---

dossierfacile-api-owner/src/main/java/fr/dossierfacile/api/dossierfacileapiowner/property/PropertyServiceImpl.java
dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/service/UserServiceImpl.java
dossierfacile-common-library/pom.xml
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/mapper/TenantCommonMapper.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/repository/AccountDeleteLogCommonRepository.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/repository/DocumentCommonRepository.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/repository/FileCommonRepository.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/repository/TenantCommonRepository.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/service/TenantCommonServiceImpl.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/service/interfaces/TenantCommonService.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/utils/LocalDateTimeTypeAdapter.java
dossierfacile-garbage-collector/pom.xml
dossierfacile-garbage-collector/src/main/java/fr/dossierfacile/garbagecollector/service/OvhServiceImpl.java
dossierfacile-garbage-collector/src/main/java/fr/dossierfacile/garbagecollector/service/ScheduledWarningService.java
dossierfacile-garbage-collector/src/main/java/fr/dossierfacile/garbagecollector/service/TenantWarningServiceImpl.java
dossierfacile-garbage-collector/src/main/java/fr/dossierfacile/garbagecollector/service/interfaces/TenantWarningService.java

feature: store data when we archive an account and full delete after a year

chore: bump openstack, refactor delete account

---

dossierfacile-api-owner/src/main/java/fr/dossierfacile/api/dossierfacileapiowner/config/ResourceServerConfig.java
dossierfacile-api-owner/src/main/java/fr/dossierfacile/api/dossierfacileapiowner/mail/ApplicantValidatedMailParams.java
dossierfacile-api-owner/src/main/java/fr/dossierfacile/api/dossierfacileapiowner/mail/MailService.java
dossierfacile-api-owner/src/main/java/fr/dossierfacile/api/dossierfacileapiowner/mail/MailServiceImplDev.java
dossierfacile-api-owner/src/main/java/fr/dossierfacile/api/dossierfacileapiowner/mail/MailServiceImplProd.java
dossierfacile-api-owner/src/main/java/fr/dossierfacile/api/dossierfacileapiowner/mail/NewApplicantMailParams.java
dossierfacile-api-owner/src/main/java/fr/dossierfacile/api/dossierfacileapiowner/property/PropertyApartmentSharingServiceImpl.java
dossierfacile-api-owner/src/main/java/fr/dossierfacile/api/dossierfacileapiowner/property/PropertyRepository.java
dossierfacile-api-owner/src/main/java/fr/dossierfacile/api/dossierfacileapiowner/user/OwnerRepository.java
dossierfacile-api-owner/src/main/java/fr/dossierfacile/api/dossierfacileapiowner/webhook/WebhookController.java
dossierfacile-api-owner/src/main/java/fr/dossierfacile/api/dossierfacileapiowner/webhook/WebhookService.java
dossierfacile-api-owner/src/main/java/fr/dossierfacile/api/dossierfacileapiowner/webhook/WebhookServiceImpl.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/repository/TenantCommonRepository.java

when tenant is updated
and when tenant has joined a property

feat(owner): Add webhook to send mail to owner

---

dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/service/UserServiceImpl.java

This reverts commit f24f0385cc8521d12d545cfbca96e52f1638d859.

Revert "feat(tenant): Move webhook after delete (#448)"

---

dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/partner/controller/ApiPartnerRegisterController.java
dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/register/form/tenant/ApplicationFormV2.java
dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/validator/anotation/tenant/application/v2/CoTenantsEmailRequiredForGroup.java
dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/validator/tenant/application/v2/CoTenantsEmailRequiredForGroupValidator.java

feat(api): add validator to check email is provided in GROUP applicationType

---

dossierfacile-garbage-collector/src/main/java/fr/dossierfacile/garbagecollector/service/ScheduledWarningService.java

we need to check relevancy for partners

feat(gc): temporary remove real account delete

---

dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/service/KeycloakServiceImpl.java

a partner may not have a keycloak account but confirm should work to handle warnings

fix(tenant): fix confirmAccount for partners

---

dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/repository/TenantLogRepository.java
dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/service/ApartmentSharingServiceImpl.java

Should now corresponds at last validation date if file is validated

feat(tenant): 🎸 modify last update date

---

dossierfacile-common-library/src/main/java/fr/dossierfacile/common/repository/TenantCommonRepository.java

Use ACCOUNT_EDITED log type to take care of FC users

feat(tenant): 🎸 send reminder mail to FC users to

---

dossierfacile-process-file/src/main/java/fr/dossierfacile/process/file/service/documentrules/IncomeTaxRulesValidationService.java
dossierfacile-process-file/src/main/java/fr/dossierfacile/process/file/service/parsers/TaxIncomeLeafParser.java
dossierfacile-process-file/src/main/resources/parsers/avisImpotsFeuillet.json
dossierfacile-process-file/src/test/java/fr/dossierfacile/process/file/service/parsers/TaxIncomeLeafParserTest.java

fix: improve leaf parser and logs

chore: improve leaf parser and add log

---

dossierfacile-process-file/src/main/java/fr/dossierfacile/process/file/service/documentrules/FranceIdentiteNumeriqueRulesValidationService.java
dossierfacile-process-file/src/main/java/fr/dossierfacile/process/file/service/parsers/FranceIdentiteParser.java

check for error status, which is returned when there is an image

✨ Feat(processfile): check for France Identite Numerique on images too

---

dossierfacile-bo/pom.xml
dossierfacile-bo/src/main/resources/application.properties

---
updated-dependencies:
- dependency-name: org.webjars:bootstrap dependency-type: direct:production ...

chore(bo): bump org.webjars:bootstrap from 3.3.7 to 5.3.3

---

dossierfacile-api-owner/pom.xml
dossierfacile-api-tenant/pom.xml
dossierfacile-api-watermark/pom.xml
dossierfacile-bo/pom.xml
dossierfacile-common-library/pom.xml
dossierfacile-pdf-generator/pom.xml
dossierfacile-process-file/pom.xml
dossierfacile-task-scheduler/pom.xml
pom.xml

The main project is at version 1.0.0 (we don't need to touch that value, we never deploy this project). The peripheral projects are versionned using a value defined inside the parent Pom.

fix: build maven and versioning

---

dossierfacile-bo/src/main/java/fr/gouv/bo/dto/MessageDTO.java
dossierfacile-bo/src/main/java/fr/gouv/bo/service/MailService.java
dossierfacile-bo/src/main/java/fr/gouv/bo/service/MessageService.java
dossierfacile-bo/src/main/java/fr/gouv/bo/service/TenantService.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/entity/Message.java

This feature need new brevo template : 
[2025a - Dossier refusé avec détail [Solo, Colocation]](https://my.brevo.com/camp/template/155/message-setup)
[2025a - Dossier refusé avec détail [Solo, Colocation - Partenaire]](https://my.brevo.com/camp/template/156/message-setup)
[2025a - Dossier refusé avec détails[Couple - Partenaire]](https://my.brevo.com/camp/template/159/message-setup)
[2025a - Dossier refusé avec détails [Couple]](https://my.brevo.com/camp/template/158/message-setup)

feature(bo): Change email when an application is refused

---

dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/controller/RegisterController.java
dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/controller/RegisterGuarantorLegalPersonController.java
dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/controller/RegisterGuarantorNaturalPersonController.java
dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/controller/RegisterGuarantorOrganismController.java
dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/partner/controller/ApiPartnerRegisterController.java
dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/partner/controller/ApiPartnerRegisterGuarantorLegalPersonController.java
dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/partner/controller/ApiPartnerRegisterGuarantorNaturalPersonController.java
dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/partner/controller/ApiPartnerRegisterGuarantorOrganismController.java
dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/security/AuthenticationFacadeImpl.java

We set a transaction at the entry point of the controller to prevent a bug where a read in database was executed while a transaction was not commited.

fix : set all register controller to transactionnal

---

dossierfacile-bo/src/main/java/fr/gouv/bo/controller/BODocumentDeniedOptionsController.java
dossierfacile-bo/src/main/java/fr/gouv/bo/dto/ItemDetail.java
dossierfacile-bo/src/main/java/fr/gouv/bo/utils/DateFormatUtil.java
dossierfacile-bo/src/main/resources/static/css/main.css
dossierfacile-bo/src/main/resources/templates/bo/apartment-sharing-view.html
dossierfacile-bo/src/main/resources/templates/bo/edit-document-denied-option.html
dossierfacile-bo/src/test/java/fr/gouv/bo/utils/DateFormatUtilTest.java

✨ Feat(bo): add placeholders for dynamic months

---

dossierfacile-bo/src/main/java/fr/gouv/bo/controller/BODocumentDeniedOptionsController.java
dossierfacile-bo/src/main/resources/templates/bo/create-document-denied-option.html

✨ Feat(bo): Add doc to create message page

---

dossierfacile-bo/src/main/java/fr/gouv/bo/controller/BODocumentDeniedOptionsController.java
dossierfacile-bo/src/main/java/fr/gouv/bo/controller/BOTenantController.java
dossierfacile-bo/src/main/java/fr/gouv/bo/repository/DocumentDeniedOptionsRepository.java
dossierfacile-bo/src/main/java/fr/gouv/bo/service/DocumentService.java

The generic checkbox can be added for ALL or for TENANT / GUARANT They will be display at the bottom of the list

feature(bo): Add bo generic checkbox

---

dossierfacile-bo/src/main/resources/templates/bo/apartment-sharing-view.html

✨ Feat(bo): add 'Guarantor' text to logs

---

dossierfacile-bo/src/main/java/fr/gouv/bo/controller/BODocumentDeniedOptionsController.java
dossierfacile-bo/src/main/java/fr/gouv/bo/utils/DocumentSubCategoryUtils.java
dossierfacile-bo/src/main/resources/messages.properties
dossierfacile-bo/src/main/resources/templates/bo/create-document-denied-option.html
dossierfacile-bo/src/main/resources/templates/bo/document-denied-options.html
dossierfacile-bo/src/main/resources/templates/bo/edit-document-denied-option.html

feature(bo): clean messages for document denied options

---

dossierfacile-process-file/src/main/java/fr/dossierfacile/process/file/barcode/twoddoc/parsing/TwoDDocData.java
dossierfacile-process-file/src/main/java/fr/dossierfacile/process/file/barcode/twoddoc/parsing/TwoDDocDataType.java
dossierfacile-process-file/src/main/resources/application.properties

- Add fields 4X and 4Y
- Don't crash on unknown fields
- Update ants tsl uri (new certificate authority FR06)

✨ Feat(processfile): Handle new 2d-doc format

---

dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/amqp/Producer.java
dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/mapper/TenantMapper.java
dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/service/DocumentServiceImpl.java
dossierfacile-api-tenant/src/main/resources/META-INF/additional-spring-configuration-metadata.json
dossierfacile-api-tenant/src/main/resources/application.properties
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/converter/ListOfBrokenRulesJsonConverter.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/entity/BlurryFileAnalysis.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/entity/DocumentAnalysisReport.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/entity/DocumentBrokenRule.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/entity/DocumentRule.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/entity/File.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/entity/ocr/BlurryResult.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/enums/BlurryFileAnalysisStatus.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/exceptions/ParsingException.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/repository/BlurryFileAnalysisRepository.java
dossierfacile-common-library/src/main/resources/db/changelog/databaseChangeLog.xml
dossierfacile-common-library/src/main/resources/db/migration/202508100000-create-blurry-file-analysis-table.xml
dossierfacile-process-file/src/main/java/fr/dossierfacile/process/file/service/AnalyzeDocumentService.java
dossierfacile-process-file/src/main/java/fr/dossierfacile/process/file/service/documentrules/AbstractPayslipRulesValidationService.java
dossierfacile-process-file/src/main/java/fr/dossierfacile/process/file/service/documentrules/BlurryRulesValidationService.java
dossierfacile-process-file/src/main/java/fr/dossierfacile/process/file/service/documentrules/FranceIdentiteNumeriqueRulesValidationService.java
dossierfacile-process-file/src/main/java/fr/dossierfacile/process/file/service/documentrules/GuaranteeProviderRulesValidationService.java
dossierfacile-process-file/src/main/java/fr/dossierfacile/process/file/service/documentrules/IncomeTaxRulesValidationService.java
dossierfacile-process-file/src/main/java/fr/dossierfacile/process/file/service/documentrules/RentalReceiptRulesValidationService.java
dossierfacile-process-file/src/main/java/fr/dossierfacile/process/file/service/documentrules/ScholarshipRulesValidationService.java

A new configuration property is available on tenant project : 
api.broken.rules.min.level.
This new configuration filter the list of broken rules returned to the frontend by level of criticality. By default only Warn and Critical are returned inside the tenant model.

Add blur analysis

---

dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/controller/DocumentController.java
dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/controller/FileController.java
dossierfacile-api-tenant/src/main/java/fr/dossierfacile/api/front/service/ApartmentSharingServiceImpl.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/entity/Document.java
dossierfacile-common-library/src/main/java/fr/dossierfacile/common/entity/Guarantor.java

feature(tenant): update the name of the watermark document downloaded
